30 8 * * * /home/dennisdlr/proyectoFinalIA/control.php 'gpio17=1'
0 17 * * * /home/dennisdlr/proyectoFinalIA/control.php 'gpio17=0'
30 9 * * * /home/dennisdlr/proyectoFinalIA/control.php 'gpio21=1'
0 16 * * * /home/dennisdlr/proyectoFinalIA/control.php 'gpio21=0'
30 10 * * * /home/dennisdlr/proyectoFinalIA/control.php 'gpio27=1'
0 15 * * * /home/dennisdlr/proyectoFinalIA/control.php 'gpio27=0'
